services:

  payment-processor-1:
    image: zanfranceschi/payment-processor:amd64-20250707101540
    networks:
      - payment-processor
    hostname: payment-processor-default
    ports:
      - 8081:8080

  payment-processor-2:
    image: zanfranceschi/payment-processor:amd64-20250707101540
    networks:
      - payment-processor
    hostname: payment-processor-fallback
    ports:
      - 8082:8080

networks:
  payment-processor:
    driver: bridge
